### ISSUE TITLE
Code generated with swift-winrt 0.6.0 fails to compile (was working with 0.5.0)

### ISSUE THREAD

**Issue by ktraunmueller** [thebrowsercompany/swift-winrt#205]
My `swift-winrt` [swift-* repos](https://github.com/ktraunmueller?tab=repositories) had been working fine with `swift-winrt` 0.5.0, but after upgrading to `swift-winrt` 0.6.0, I am seeing compilation issues:

```
E:\sandbox\ktraunmueller\winrt\swift-windowsfoundation\Sources\WindowsFoundation\Generated\Windows.Foundation+ABI.swift:488:84: error: argument type 'UUID' does not conform to expected type 'Decoder'
                try CHECKED(pThis.pointee.lpVtbl.pointee.Equals(pThis, .init(from: target), .init(from: value), &result))
                                                                                   ^
                                                                                          as! Decoder
E:\sandbox\ktraunmueller\winrt\swift-windowsfoundation\Sources\WindowsFoundation\Generated\Windows.Foundation+ABI.swift:488:73: error: referencing initializer 'init(from:)' on 'Optional' requires that 'UnsafePointer<GUID_Workaround>' conform to 'Decodable'
                try CHECKED(pThis.pointee.lpVtbl.pointee.Equals(pThis, .init(from: target), .init(from: value), &result))
                                                                        ^
Swift.Optional:1:11: note: where 'Wrapped' = 'UnsafePointer<GUID_Workaround>'
extension Optional : Decodable where Wrapped : Decodable {
          ^
E:\sandbox\ktraunmueller\winrt\swift-windowsfoundation\Sources\WindowsFoundation\Generated\Windows.Foundation+ABI.swift:488:105: error: argument type 'UUID' does not conform to expected type 'Decoder'
                try CHECKED(pThis.pointee.lpVtbl.pointee.Equals(pThis, .init(from: target), .init(from: value), &result))
                                                                                                        ^
                                                                                                              as! Decoder
E:\sandbox\ktraunmueller\winrt\swift-windowsfoundation\Sources\WindowsFoundation\Generated\Windows.Foundation+ABI.swift:488:94: error: referencing initializer 'init(from:)' on 'Optional' requires that 'UnsafePointer<GUID_Workaround>' conform to 'Decodable'
                try CHECKED(pThis.pointee.lpVtbl.pointee.Equals(pThis, .init(from: target), .init(from: value), &result))
                                                                                             ^
Swift.Optional:1:11: note: where 'Wrapped' = 'UnsafePointer<GUID_Workaround>'
extension Optional : Decodable where Wrapped : Decodable {
...
```

I hope this should be reproducible with the `swift-winrt-060` branches in my [swift-windowsfoundation](https://github.com/ktraunmueller/swift-windowsfoundation) and [swift-cwinrt](https://github.com/ktraunmueller/swift-cwinrt) repos.

<details>
<summary>Swift toolchain diagnostics</summary>

Toolchain: [20250310.3](https://github.com/thebrowsercompany/swift-build/releases/tag/20250310.3)
```
compnerd.org Swift version 6.2-dev (LLVM 1c65036ec40f6bd, Swift 082aaecc9caa6ec)
Platform: win32
Swift Path: E:\Swift\Toolchains\0.0.0+Asserts\usr\bin
Toolchain Path: E:\Swift\Toolchains\0.0.0+Asserts\usr
Runtime Library Path: E:\Swift\Runtimes\0.0.0\usr\bin
Default Target: aarch64-unknown-windows-msvc
Default SDK: E:\Swift\Platforms\0.0.0\Windows.platform\Developer\SDKs\Windows.sdk\
XCTest Path: E:\Swift\Platforms\0.0.0\Windows.platform\Developer\Library\XCTest-development\usr\bin64a
Settings:
{
  "path": "e:\\Swift\\Toolchains\\0.0.0+Asserts\\usr\\bin",
  "buildArguments": [],
  "packageArguments": [],
  "additionalTestArguments": [],
  "testEnvironmentVariables": {},
  "sanitizer": "off",
  "searchSubfoldersForPackages": false,
  "autoGenerateLaunchConfigurations": true,
  "disableAutoResolve": false,
  "diagnosticsCollection": "keepSourceKit",
  "diagnosticsStyle": "llvm",
  "backgroundCompilation": false,
  "actionAfterBuildError": "Focus Terminal",
  "buildPath": "",
  "disableSwiftPackageManagerIntegration": false,
  "warnAboutSymlinkCreation": true,
  "enableTerminalEnvironment": true,
  "pluginPermissions": {},
  "attachmentsPath": ".build/attachments",
  "excludeFromCodeCoverage": [],
  "excludePathsFromPackageDependencies": [
    ".git",
    ".github"
  ],
  "showBuildStatus": "swiftStatus",
  "showCreateSwiftProjectInWelcomePage": true,
  "openAfterCreateNewProject": "prompt",
  "sourcekit-lsp": {
    "serverPath": "",
    "serverArguments": [],
    "supported-languages": [
      "swift",
      "objective-c",
      "objective-cpp",
      "c",
      "cpp"
    ],
    "backgroundIndexing": "on",
    "trace": {
      "server": "off"
    },
    "disable": false
  },
  "debugger": {
    "useDebugAdapterFromToolchain": true,
    "path": ""
  },
  "swiftEnvironmentVariables": {
    "DEVELOPER_DIR": "public"
  },
  "runtimePath": "",
  "SDK": "",
  "swiftSDK": "",
  "diagnostics": false
}
```
</details>

**Comment by stevenbrix** [comment]
hmm strange, i'll take a look

**Comment by stevenbrix** [comment]
@ktraunmueller i'm able to repro the issue and will work on a fix. in the meantime, if you don't need the `GuidHelper` API you could add that to your exclusion list for the time being
